-- Create usage_log table (for cc-usage-web uploads)
-- Mirrors ~/lib/cc-usage SPEC.md schema

create table if not exists usage_log (
  id bigint generated by default as identity primary key,
  session_id text not null,
  source text not null,
  project text,
  model text,
  input_tokens integer default 0,
  output_tokens integer default 0,
  cache_creation_tokens integer default 0,
  cache_read_tokens integer default 0,
  cost_usd real default 0,
  timestamp timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_usage_source on usage_log(source);
create index if not exists idx_usage_timestamp on usage_log(timestamp);
create index if not exists idx_usage_session on usage_log(session_id);

-- RLS
alter table usage_log enable row level security;

-- Anonymous access (tighten later)
create policy "Allow anonymous inserts" on usage_log
  for insert with check (true);

create policy "Allow anonymous reads" on usage_log
  for select using (true);
